### ISSUE TITLE
Failed initializing MeCab.

### ISSUE THREAD

**Issue by 3eeps** [SamuraiT/mecab-python3#101]
hello! things seem to install fine ish, but I still get this error after trying the "Common Issues" part of the readme:

issueを英語で書く必要はありません。
```
arguments:
default dictionary path: C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\unidic\dicdir
[ifs] no such file or directory: C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\unidic\dicdir\dicrc
```
the file is in that location. not sure whats up!

**Comment by polm** [comment]
Does it work if you use `unidic-lite` and uninstall `unidic`? 

After installing `unidic`, did you do the manual download step? `python -m unidic download`

How did you install fugashi, what version is it, and what is the code you are executing that produces the above error? It is very unusual for `arguments:` to be blank.

**Comment by 3eeps** [comment]
i missed this `python -m unidic download`. this fixed my issue! thanks!
