### ISSUE TITLE
Meet fatal error when install mecab python3 for openvoice and myshell-ai/MeloTTS

### ISSUE THREAD

**Issue by irrikrlla** [SamuraiT/mecab-python3#104]
Installing openvoice and myshell-ai/MeloTTS required mecab-python3 == 1.0.5. However, I cannot install the version of mecab-python3, which is very weird, even my Windows has the vs 2022 build tool. 
![屏幕截图 2024-06-30 174330](https://github.com/SamuraiT/mecab-python3/assets/46410613/8cfbc776-2b65-4699-9f08-5cec693fc27c)
![屏幕截图 2024-06-30 174348](https://github.com/SamuraiT/mecab-python3/assets/46410613/86246d81-a391-4491-afc8-6c862de1355c)

**Comment by polm** [comment]
Please install more recent version of the library, such as 1.0.9. 1.0.5 is from two years ago and doesn't have wheels for Python 3.11.
