### ISSUE TITLE
Add wheels on Pypi

### ISSUE THREAD

**Issue by chezou** [SamuraiT/mecab-python3#16]
Since wheel format is standard for distributing Python packages, it would be nice if we can get wheel from Pypi.

**Comment by zackw** [comment]
I agree, we should have both wheels and official source releases on PyPI.  @SamuraiT do you have any plans for this or should I look into it?

**Comment by SamuraiT** [comment]
nice to have it. please look into it!

**Comment by zackw** [comment]
I've successfully uploaded a source distribution of 0.996.1 to PyPI.  Wheels to follow as soon as I figure out how to persuade Travis to build them.

**Comment by chezou** [comment]
I've succeeded to build manylinux1 wheel on travis-ci. https://github.com/chezou/mecab-python3/tree/release-wheel
Currently working on OSX wheel build.

**Comment by chezou** [comment]
@miinhtn I've sent a PR and once it will be merged, you can get a wheel for linux. I'm waiting for review.

**Comment by miinhtn** [comment]
@chezou actually I visited your github and downloaded the wheel file. It worked (in my simple test) like charm on OSX. :+1:  but wonder how it gonna be on linux

**Comment by zackw** [comment]
@chezou I don't expect to have time to review your patches properly until next week.  Sorry for the delay, day job is in crunch mode right now.

**Comment by chezou** [comment]
Thanks @zackw for taking care of it. I didn't mean to rush you. Feel free to tell me your advice since there would be some design discussion.

Anyway, I understand your effort is volunteer based one but tell me if there's anything I can help.

**Comment by zackw** [comment]
Release candidate wheels are now available for Mac and Linux at https://test.pypi.org/project/mecab-python3/0.996.2rc2/ , please test them. Thank you everyone for your patience. We plan to make a new official release in the next couple of weeks.

Windows wheels are in the works but I can't give any time frame for them, sorry.

**Comment by zackw** [comment]
0.996.2 has been released with wheels for Mac and Linux.  I am going to close this issue and make a new one specifically for Windows wheels.
