### ISSUE TITLE
Installation error of mecab-python3

### ISSUE THREAD

**Issue by YuhkiYano** [SamuraiT/mecab-python3#20]
I tried "pip install mecab-python3"  command on Ubuntu 16.04. 
However, following error has caused.

```
Collecting mecab-python3
  Using cached https://files.pythonhosted.org/packages/ac/48/295efe525df40cbc2173748eb869290e81a57e835bc41f6d3834fc5dad5f/mecab-python3-0.996.1.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: mecab-config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-36rkqtiy/mecab-python3/setup.py", line 29, in <module>
        inc_dir  = mecab_config("--inc-dir")
      File "/tmp/pip-install-36rkqtiy/mecab-python3/setup.py", line 27, in mecab_config
        return os.popen("mecab-config " + arg).readlines()[0].split()
    IndexError: list index out of range

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-36rkqtiy/mecab-python3/
```

If you have some comments, please contact me by comment.

**Comment by zackw** [comment]
`/bin/sh: 1: mecab-config: not found`

The PyPI source tarball is not self-contained.  You must first install the Ubuntu `libmecab-dev` package and at least one MeCab dictionary (another Ubuntu package, named `mecab-[something]dic`; there are several options and I don't know what the differences are).  That should bring in everything else you need.

Binary wheels will be made available Real Soon Now that will not have this problem, but we don't plan on changing the contents of the source distribution.
