### ISSUE TITLE
Can't install in Virtual Enviroment [python3]

### ISSUE THREAD

**Issue by miinhtn** [SamuraiT/mecab-python3#23]
I have successfully installed mecab, ipadic and relevant packages on my laptop (running Ubuntu) also mecab-python3 using pip (tested and ran successfully). However, when it comes to virtual environment, it failed to install mecab-python3.  The error prompt up as follows
`MeCab_wrap.cpp:173:11: fatal error: Python.h: No such file or directory
     # include <Python.h>
               ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`
In this case, do you have any suggestion on installing it on the virtual environment? Thanks

**Comment by zackw** [comment]
This error means you don't have the CPython development headers and libraries installed in your virtual environment.  Can you tell me some more about what you mean by "virtual environment"?  There are several different possibilities and without more detail I can't give more specific advice or know whether there's anything that needs to be changed in the mecab-python3 packaging.

**Comment by zackw** [comment]
That's bizarre.  I don't know why a Python virtualenv would be unable to access the CPython development headers, or what you're supposed to do about it.  But I don't think this is a problem with our setup.py, I think there's something you need to do to make available the headers needed for compiled-code modules.
