### ISSUE TITLE
Is it possible to unset output-format-type?

### ISSUE THREAD

**Issue by polm** [SamuraiT/mecab-python3#25]
I would like to specify a custom format string even if the user has an `output-format-type` specified in their `mecabrc`. As described in https://github.com/taku910/mecab/issues/41, the way to do this on the command line is to give an argument like `-O ""`. So I tried this:

    tagger = MeCab.Tagger('-O ""')

Unfortunately this results in a `RuntimeError`. I tried escaping the quotes without effect. I guess something about the way the argument string is passed to the Mecab library is different than its own internal argument handling?

For reference, the reason I want to specify a format string is explained in https://github.com/explosion/spaCy/pull/3491.

**Comment by zackw** [comment]
Unfortunately, the SWIG interface definition file that we use only exposes the C++-level Tagger constructor that takes a single string containing command-line options.  That constructor doesn't implement any shell quotation syntax; it blindly splits its input on whitespace.  It is therefore not possible to set the `-O` option's argument to the empty string using this constructor.

There is another constructor that takes an _array_ of command-line options.  If we exposed that constructor, you could write something like

    tagger = MeCab.Tagger(["-O", ""])

and it would work.  Unfortunately, I do not understand SWIG well enough to know how to make that change.  If you can figure it out I would be glad to merge your patch.  (Please note that both the Tagger and Model classes should be changed.)
