### ISSUE TITLE
MeCab -b option

### ISSUE THREAD

**Issue by loretoparisi** [SamuraiT/mecab-python3#26]
To support the command line options `mecab -Owakati -b5000`, is it ok to call it like

```python
mecab = MeCab.Tagger("-Owakati -b5000")
```

**Comment by zackw** [comment]
That should work, yes.

We are preparing a new release, with several important bugs fixed and based on a newer version of the MeCab library.  If 0.7 is not working for you, please try the wheels at https://test.pypi.org/project/mecab-python3/0.996.2rc2/ .

**Comment by zackw** [comment]
Version 0.996.2 has now been released and can be installed from PyPI using `pip`.  If you are still having problems with the `-b` option with this version, please reopen this issue and describe in detail what happened and what you wanted to happen instead.
