### ISSUE TITLE
Provide binary wheels for Windows

### ISSUE THREAD

**Issue by zackw** [SamuraiT/mecab-python3#31]
As of version 0.996.2, we are now providing binary wheels to PyPI for Mac and Linux.  The extension module in these wheels is statically linked against libmecab, and there is a precompiled dictionary (using ipadic) that the library is instructed to use.

We would like to provide binary wheels for Windows as well.  To do this, we need all of the following:

* [ ] A CI environment that can build binaries for Windows -- either running on Windows itself, or cross-compiling.  This must be able to match the ABI used by the [official Python builds for Windows](https://www.python.org/downloads/windows/).  [AppVeyor](https://www.appveyor.com/) is the obvious choice since [cibuildwheel](https://github.com/joerick/cibuildwheel) already knows how to work with it.
* [ ] Scripting to install [SWIG](http://www.swig.org/) in this CI environment, either from a [prebuilt package](https://chocolatey.org/packages?q=swig) or from source.
* [ ] Scripting to download [`mecab-ipadic`](https://github.com/taku910/mecab/tree/master/mecab-ipadic) and generate a compiled dictionary from it.  This will involve either installing or building the MeCab command-line tools.
* [ ] Scripting to build the libmecab library for each supported interpreter, matching the ABI and compilation settings for Python extension modules for that interpreter.
* [ ] Logic in `scripts/travis-build.py` and `scripts/travis-deploy.py` to wire all of this together, as they currently do for OSX and Linux.  (Despite the names, it shouldn't be necessary to rewrite them from scratch for AppVeyor.

Anyone who is interested in working on this should first familiarize themselves with the [existing build scripts](https://github.com/SamuraiT/mecab-python3/tree/master/scripts), which should be extended, rather than duplicated, to the maximum extent possible.

I don't have any plans to work on this myself.

**Comment by clausagerskov** [comment]
is it at all possible to install in windows?

**Comment by zackw** [comment]
It is theoretically possible to build the package from source on Windows
but I’ve never tried it and I would expect it to be buggy. Binary wheels
would require fixing all of those bugs *and* a tool that does on Windows
what auditwheel does on Linux; as far as I know no one has written one yet
(see https://discuss.python.org/t/delocate-auditwheel-but-for-windows/2589
).

I don’t intend to work on this myself. If someone wanted to pay for it to
be done, they should hire someone with substantial experience with *both*
Python and C++ on Windows. I am not that person.

**Comment by polm** [comment]
I don't have a Windows build environment to check, but as Zack said it should work on Windows in theory. 

[fugashi](https://github.com/polm/fugashi) has Windows wheels thanks to a user contribution, I could try to bring those build scripts to this repo.

**Comment by polm** [comment]
I've been working on this and I think I have wheels working. The solution basically copies the script from fugashi that builds Windows wheels. In contrast to the original suggestions:

- Github Actions are used. These weren't an option when this was originally posted, but they're more convenient than external services.
- SWIG is not used at build time. Instead the SWIG-generated C++ file is just included in the repo. While SWIG provides a binary Windows distribution it's easier to just not have to deal with it. (This also affects Linux and OSX.)
- ipadic is not bundled
- A prebuilt MeCab is used rather than compiling it.

I have pushed the changes in the `windows-action` branch and you should be able to install the wheels like so:

    pip install mecab-python3==0.996.6rc4

Note this includes the changes related to dropping ipadic for pypi-provided unidic.

Some of the Linux builds are failing for unclear reasons, but I'll get that sorted out. If this works Then it will likely be a 1.0 release rather than 0.996.6.

**Comment by BramVanroy** [comment]
Would be great to have prebuilt wheels working for Windows 64 bit. Currently installation fails. This library is a a dependency of `https://github.com/huggingface/transformers` for testing, so it would be great if we could also test on Windows. Thanks for all your work!

**Comment by polm** [comment]
Howdy Bram, thanks for the report. Could you try the latest alpha and tell me what errors you get if any?

    pip install mecab-python3==1.0.0a1

**Comment by BramVanroy** [comment]
Hi, thanks for your quick reply!

Installation now goes through successfully. After installing unidic-lite and vc_redist, the tests also pass. However, the example in the README fails in the second part with `-Ochasen`.

```python
>>> import MeCab
>>> wakati = MeCab.Tagger("-Owakati")  # works!
>>> wakati.parse("pythonが大好きです").split()
['python', 'が', '大好き', 'です']

>>> chasen = MeCab.Tagger("-Ochasen")  # fails!
>>> print(chasen.parse("pythonが大好きです"))
python　python　　python　名詞-固有名詞-組織
が　　　ガ　　　　が　　　助詞-格助詞-一般
大好き　ダイスキ　大好き　名詞-形容動詞語幹
です　　デス　　　です　　助動詞　特殊・デス　基本形
EOS

The error is simply a RuntimeError:

```bash
>>> chasen = MeCab.Tagger("-Ochasen")
  File "lib\site-packages\MeCab\__init__.py", line 102, in __init__
    super(Tagger, self).__init__(args)
RuntimeError
```

**Comment by polm** [comment]
Thanks for confirming!

> However, the example in the README fails in the second part with -Ochasen.

Ah, I need to update the README - chasen output format isn't supported by Unidic. (This is actually the same as #45). I'll do that now.

**Comment by BramVanroy** [comment]
Cool, in that case I think that your recent endeavours were very fruitful, since it now seems to work well on Windows for me. Great job!

**Comment by HeroadZ** [comment]
hey, guys. I follow the installation of unidic, vc_redist and mecab-python3==1.0.0a1. 
But got an importError. Is there any advice?

**Comment by polm** [comment]
@HeroadZ Can you show your code? Also, please check you have the capitalization of `MeCab` correct.

**Comment by HeroadZ** [comment]
@polm 
```
C:\Users\Merli>pip install mecab-python3==1.0.0a1
Requirement already satisfied: mecab-python3==1.0.0a1 in c:\users\merli\anaconda3\lib\site-packages (1.0.0a1)

C:\Users\Merli>pip install unidic-lite
Requirement already satisfied: unidic-lite in c:\users\merli\anaconda3\lib\site-packages (1.0.6)

>>> import MeCab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Merli\anaconda3\lib\site-packages\MeCab\__init__.py", line 10, in <module>
    from . import _MeCab
ImportError: DLL load failed: 找不到指定的模块。
```

windows 10 64bit and Anaconda 3 python 3.7

**Comment by polm** [comment]
Hm, maybe an Anaconda issue, though when I tried it worked for me here. 

Do you have a DLL file in `c:\Users\Merli\anaconda3\Lib\site-packages\MeCab\`?

**Comment by HeroadZ** [comment]
@polm yes, there's a DLL file called `libmecab.dll`

**Comment by polm** [comment]
Hm, maybe it's a path issue then... Could you try installing [fugashi](https://github.com/polm/fugashi) and seeing if that works?

**Comment by HeroadZ** [comment]
I installed fugashi and it works well.
```
>>> from fugashi import Tagger
>>> tagger = Tagger('-Owakati')
>>> tagger.parse("麩菓子は、麩を主材料とした日本の菓子。")
'麩 菓子 は 、 麩 を 主材 料 と し た 日本 の 菓子 。'
```

**Comment by polm** [comment]
In that case I'm not sure what the issue could be :/ Let me open a new issue and try to get more testers. Sorry for the trouble.

**Comment by HeroadZ** [comment]
> In that case I'm not sure what the issue could be :/ Let me open a new issue and try to get more testers. Sorry for the trouble.

Thank you very much. And sorry for my poor knowledge on these things.

**Comment by polm** [comment]
No worries, packaging is difficult, especially on Windows.

**Comment by HeroadZ** [comment]
And I found two alternatives before the fix of this problem.

First is [janome](https://github.com/mocobeta/janome), which is written in pure python.

Second is to first install a .exe in windows which can be found [here](https://github.com/ikegami-yukino/mecab/releases), and then run command
```
pip install mecab
```

I don't know the difference between these projects, but they are all able to analyze Japanese. Helps a lot.

**Comment by polm** [comment]
My understanding is that the `mecab` project was originally written because this package didn't have Windows support. You can read more about it [here](https://qiita.com/yukinoi/items/990b6933d9f21ba0fb43) (in Japanese).

**Comment by polm** [comment]
1.0 has been officially released with Windows wheels.
