### ISSUE TITLE
How can I  set the output-format-type with cpp API?

### ISSUE THREAD

**Issue by SefaZeng** [SamuraiT/mecab-python3#32]
I want to use the cpp API of MeCab, but its example do not show how to set the options.I tried this:
`MeCab::Tagger *tagger = MeCab::createTagger("-Owakati");`
But it doesn't work, and return exception.But no message print. Do you know how to use it? I just want to split the sentence with wakati mode.
Any help is appreciate ! Thx!

**Comment by zackw** [comment]
I regret to say we cannot help you with the C++ API to MeCab.  We only maintain a Python wrapper, not MeCab itself.
