### ISSUE TITLE
Wheels not installed on Debian

### ISSUE THREAD

**Issue by polm** [SamuraiT/mecab-python3#39]
@KoichiYasuoka [reports](https://github.com/SamuraiT/mecab-python3/pull/37#issuecomment-568996994) that there are no wheels for the new 0.996.3 version. 

This is the first release I have done. Pushing a tag to the git repo created a new release on PyPI, as I expected, but it's possible I have to do something else to build wheels. I am looking into it.

**Comment by polm** [comment]
Looking [at PyPI](https://pypi.org/project/mecab-python3/0.996.3/#files), it looks like there are wheels for 0.996.3 just like there are for 0.996.2. Maybe an intermediary server hasn't been updated yet since the release just happened?

> But I think it's incompatible (in installing) from 0.996.2...

@KoichiYasuoka can you clarify what you mean by that? Are you also unable to install wheels for 0.996.2? There was the memory issue and some other bugs but as far as I'm aware installing wheels and using `parse` should be fine.

**Comment by KoichiYasuoka** [comment]
When I install mecab-0.996.2 in my Debian it downloads `mecab_python3-0.996.2-cp37-cp37m-manylinux1_x86_64.whl` binary wheel, and safely installed. But for mecab-0.996.3 it downloads `mecab-python3-0.996.3.tar.gz` and failed. Umm... `manylinux2010` from `manylinux1`...

**Comment by polm** [comment]
Good catch on the `manylinux2010` change. It looks like something in Travis changed in November that made `manylinux2010` the preferred wheel format, but it's not supported on older versions of pip. What's your pip version? Is upgrading it an option?

See [this issue](https://github.com/pymupdf/PyMuPDF/issues/400) for more details.

**Comment by KoichiYasuoka** [comment]
My Debian's pip version is `pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)` and I've just found [PEP 571](https://www.python.org/dev/peps/pep-0571/) mentions:

>1. The wheel may only contain binary executables and shared objects compiled for one of the two architectures supported by CentOS 6: x86_64 or i686.

**Comment by polm** [comment]
OK, thanks for the confirmation. It looks like `manylinux2010` support was added in pip 19.0, so that makes sense. 

Based on the [cibuildwheel docs](https://pypi.org/project/cibuildwheel/) it should be possible to build both `manylinux1` and `manylinux2010` wheels, I'll look into how.

**Comment by KoichiYasuoka** [comment]
I've tried to edit .travis.yml as shown in [this PR](https://github.com/polm/mecab-python3/pull/2), but I'm vague whether it works on Travis CI.

**Comment by polm** [comment]
Happy New Year, and thanks for your patience with this. I created a new version 0.996.4rc2 and the `manylinux1` wheels appear to have built successfully, can you verify they install correctly?

**Comment by KoichiYasuoka** [comment]
Thank you @polm , and I've just tried `pip3 install mecab-python3==0.996.4rc2` in my new Debian machine with pip 18.1. Yes, OK, it is installed perfectly and works well with my `UD-Kanbun` and `UniDic2UD`. Thank you again.

**Comment by polm** [comment]
Excellent, glad to hear it works! Thanks for the PR.

**Comment by KoichiYasuoka** [comment]
Hi @polm, do you have a plan to make 0.996.4rc2 into the main release?

**Comment by polm** [comment]
Good point, I'll make it an official release. Sorry for not doing that sooner.

**Comment by polm** [comment]
Just a note that the Travis builds are having trouble with some of the older Python versions, so this might take a little bit to get released. Thank you for your patience.

**Comment by polm** [comment]
I managed to resolve the build issues and a new version with these changes should be released shortly. 

Note that 0.996.4 had issues with Travis, so the new latest version will skip 4 and be 0.996.5.

**Comment by KoichiYasuoka** [comment]
Thank you @polm, I've just tried `pip3 install -U mecab-python3` and got new `mecab_python3-0.996.5-cp37-cp37m-manylinux1_x86_64.whl`.
