### ISSUE TITLE
OSX Travis Build issues

### ISSUE THREAD

**Issue by polm** [SamuraiT/mecab-python3#41]
The OSX Travis build is having issues, here's an error from a recent build:

```
==================================== ERRORS ====================================
_____________________ ERROR collecting test/test_basic.py ______________________
ImportError while importing test module '/Users/travis/build/SamuraiT/mecab-python3/test/test_basic.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
build/SamuraiT/mecab-python3/test/test_basic.py:11: in <module>
    import MeCab
/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmpnv9t1mp4/lib/python3.5/site-packages/MeCab/__init__.py:10: in <module>
    from . import _MeCab
E   ImportError: dlopen(/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmpnv9t1mp4/lib/python3.5/site-packages/MeCab/_MeCab.cpython-35m-darwin.so, 2): Symbol not found: __ZNSs4_Rep11_S_terminalE
E     Referenced from: /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmpnv9t1mp4/lib/python3.5/site-packages/MeCab/_MeCab.cpython-35m-darwin.so
E     Expected in: flat namespace
E    in /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmpnv9t1mp4/lib/python3.5/site-packages/MeCab/_MeCab.cpython-35m-darwin.so
```

It looks like the library is not being built correctly. Unfortunately, I don't have a Mac, so it's difficult for me to troubleshoot this. Any help would be appreciated.

**Comment by polm** [comment]
So after trying different build configurations, there were two issues with the build. One was that cibuildwheel recently added pypy support and that doesn't work on any platform (may be a swig issue). However, this symbol issue on 3.5 on OSX appears to be unrelated to pypy. 

For now I'm just going to disable 3.5 on OSX, but if anyone has any insight into why this is happening let me know.

**Comment by HiromuHota** [comment]
I don't have an answer why the issue was happening, but ICYMI
- Python 3.5 is end-of-life on 2020-09-13. https://devguide.python.org/#status-of-python-branches
- You can ssh login to the Travis job and do some debugs even for Mac (https://docs.travis-ci.com/user/running-build-in-debug-mode/#connecting-to-the-job-running-in-the-debug-mode)

**Comment by polm** [comment]
Given 3.5 will reach end-of-life soon I'm going to leave this alone for now, but if someone has a fix I can integrate it.
