### ISSUE TITLE
Installation Issue on PowerPC

### ISSUE THREAD

**Issue by marwash25** [SamuraiT/mecab-python3#42]
Hello, 

I am running `pip install mecab-python3`. I get the following error: 

```
Building wheel for mecab-python3 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /nobackup/users/marwash/anaconda3/envs/wmlce-1.6.2/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i25j7f3o/mecab-python3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i25j7f3o/mecab-python3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6fobdwlz
       cwd: /tmp/pip-install-i25j7f3o/mecab-python3/
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-ppc64le-3.7
  creating build/lib.linux-ppc64le-3.7/MeCab
  copying src/MeCab/__init__.py -> build/lib.linux-ppc64le-3.7/MeCab
  running build_ext
  error: [Errno 2] No such file or directory: 'mecab-config': 'mecab-config'
  ERROR: Failed building wheel for mecab-python3
  Running setup.py clean for mecab-python3
Failed to build mecab-python3
```

Any advice on how can I fix this?

**Comment by polm** [comment]
It looks like pip is trying to build the package from source but you don't have MeCab installed. 

What OS (and version) are you running this on? Wheels are available for Linux and OSX and should be used when installing normally.

Alternately, you can try installing MeCab first. See these [instructions for installing MeCab](https://www.dampfkraft.com/nlp/japanese-spacy-and-mecab.html) (you can ignore the spaCy parts).

**Comment by marwash25** [comment]
I am running this on a HPC cluster with Linux Redhat.

**Comment by polm** [comment]
Hm, in that case maybe pip isn't using the wheels because you aren't on a supported architecture (x86_64 or i686). 

What is the output of `uname -a`?

If you aren't on a supported architecture, you'll need to install MeCab and make sure that `mecab-config` is in your `PATH`. You'll also need SWIG.

**Comment by marwash25** [comment]
The output of `uname - a` is
`Linux service0001 4.14.0-115.10.1.el7a.ppc64le #1 SMP Wed Jun 26 09:32:17 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux`

**Comment by polm** [comment]
OK, that means you're on a PPC architecture, which we don't have wheels for. You'll have to install MeCab from source in order to install mecab-python3.

**Comment by polm** [comment]
I'm going to close this, but if you are having other errors with installation let me know and I may be able to help.
