### ISSUE TITLE
typo in release note 1.0.0

### ISSUE THREAD

**Issue by kfjt** [SamuraiT/mecab-python3#48]
1.0.0 release おめでとうございます, ありがたく活用させていただいています.

[1.0.0 の リリースページ](https://github.com/SamuraiT/mecab-python3/releases/tag/1.0.0) に

`pip install mecab-python3[undici-lite]`
と書かれています.

`pip install mecab-python3[unidic-lite]`
が正しいつづりです.

リリースページはプルリクに出来ないためissueで失礼します.

**Comment by polm** [comment]
ご報告ありがとうございます、修正しました。
