### ISSUE TITLE
Is there any plan to publish pip-installable "ipadic"?

### ISSUE THREAD

**Issue by tamuhey** [SamuraiT/mecab-python3#49]
Hi, congrats on the release `v1.0.0`!

As I mentioned in the title, Is there any plan to publish pip-installable `ipadic`?
`mecab-python3` previously bundled ipadic in it, and I want to use it with version>=1.0.

**Comment by polm** [comment]
I hadn't been planning on it but multiple people have asked so I might as well. Give me a week or two to get to it.

**Comment by polm** [comment]
Test version of ipadic is out, `pip install ipadic==1.0.0a2`. I think it works but let me know if there are any issues.

After it's had a bit of testing I'll make an official release.

**Comment by polm** [comment]
Code is here: https://github.com/polm/ipadic-py

**Comment by polm** [comment]
Just released version 1.0 of ipadic on PyPI. 

https://pypi.org/project/ipadic/
