### ISSUE TITLE
RuntimeError on CentOS

### ISSUE THREAD

**Issue by foxonspace** [SamuraiT/mecab-python3#50]
Errors appeared when I trying to run .sh file:
```
----------------------------------------------------------------------
Failed when trying to initialize MeCab. Some things to check:

    - If you are not using a wheel, do you have mecab installed?

    - Do you have a dictionary installed? If not do this:

        pip install unidic-lite

    - If on Windows make sure you have this installed:

        https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

    - Try creating a Model with the same arguments as your Tagger; that may
      give a more descriptive error message.

If you are still having trouble, please file an issue here:

    https://github.com/SamuraiT/mecab-python3/issues
Traceback (most recent call last):
  File "/opt/faqsearch_engine/src/create_corpus_wiki_main.py", line 81, in <module>
    main(conf_file,args[1],args[2],args[3])
  File "/opt/faqsearch_engine/src/create_corpus_wiki_main.py", line 38, in main
    tagger = MeCabWp(config.sysdic, config.userdic)
  File "/opt/faqsearch_engine/src/MeCabWp.py", line 48, in __init__
    self.tagger = MeCab.Tagger( option )
  File "/usr/lib64/python3.5/site-packages/MeCab/__init__.py", line 105, in __init__
    super(Tagger, self).__init__(args)
RuntimeError
-------------------------------
```

I did:
1. install pip3.5
2. install pip3.5 unidic-lite

But still not fixed, any reccommends?

**Comment by polm** [comment]
1. What is the output of `mecab-py-info`?
2. What is your operating system?
3. You seem to be using a MeCab wrapper (MeCabWp). What arguments are you actually passing to the Tagger?

**Comment by foxonspace** [comment]
Thank you for the reply. 
I was recieved the work from my senior colleague, so I am not sure if I could answer as detailed as you expected:

1. , 3.
FAQSEARCH_ENGINE_DIR='/opt/faqsearch_engine'
WIKI_TEXT=${FAQSEARCH_ENGINE_DIR}/data/wiki_all.txt
WORK_TEXT=${FAQSEARCH_ENGINE_DIR}/data/wiki_all_w.txt
WIKI_DIR=${FAQSEARCH_ENGINE_DIR}/data/wiki/text/AA
PREFIX='wiki'

cd ${FAQSEARCH_ENGINE_DIR}/src
/bin/python3.5 ${FAQSEARCH_ENGINE_DIR}/src/create_corpus_wiki_main.py ${WIKI_DIR} ${PREFIX} ${WORK_TEXT}
sed -e "s/http:\/\/ //g" ${WORK_TEXT} > ${WIKI_TEXT}

2. CentOS Linux release 7.8.2003 (Core)

**Comment by foxonspace** [comment]
> What is the output of mecab-py-info?
> What is your operating system / Linux distribution?
> You seem to be using a MeCab wrapper (MeCabWp). What arguments are you actually passing to the Tagger?

Thank you for the reply.
I was recieved the work from my senior colleague, so I am not sure if I could answer as detailed as you expected:
, 3.
FAQSEARCH_ENGINE_DIR='/opt/faqsearch_engine'
WIKI_TEXT=${FAQSEARCH_ENGINE_DIR}/data/wiki_all.txt
WORK_TEXT=${FAQSEARCH_ENGINE_DIR}/data/wiki_all_w.txt
WIKI_DIR=${FAQSEARCH_ENGINE_DIR}/data/wiki/text/AA
PREFIX='wiki'
cd ${FAQSEARCH_ENGINE_DIR}/src
/bin/python3.5 ${FAQSEARCH_ENGINE_DIR}/src/create_corpus_wiki_main.py ${WIKI_DIR} ${PREFIX} ${WORK_TEXT}
sed -e "s/http:// //g" ${WORK_TEXT} > ${WIKI_TEXT}
CentOS Linux release 7.8.2003 (Core)

**Comment by polm** [comment]
Thanks for letting me know you're using CentOS. 

I don't know what those environment variables are, and they aren't helpful for solving your problem.

This is line 48 of MeCabWp.py:

    > self.tagger = MeCab.Tagger( option )

Can you tell me what the value of `option` is? You probably have to change that to fix your problem.If your code is online somewhere, can you give me a link to it?

**Comment by foxonspace** [comment]
Hello.
Thank you for a reply.
I was able to solved the Runtim Error by update my python to python3.6

However, I still having a problem with mecab here.
--------------
[root@Chatbot faqsearch_engine]# cd sh
[root@Chatbot sh]# ./2_create_corpus_wiki.sh
Traceback (most recent call last):
  File "/opt/faqsearch_engine/src/create_corpus_wiki_main.py", line 14, in <module>
    from MeCabWp import MeCabWp
  File "/opt/faqsearch_engine/src/MeCabWp.py", line 14, in <module>
    import MeCab
ModuleNotFoundError: No module named 'MeCab'
-----------------

However, I am certain that I have installed mecab, so the problem is still unsolved.
------
[root@Chatbot sh]# mecab
あいうえお
あい    動詞,自立,*,*,五段・カ行イ音便,連用タ接続,あく,アイ,アイ
う      助動詞,*,*,*,不変化型,基本形,う,ウ,ウ
え      フィラー,*,*,*,*,*,え,エ,エ
お      感動詞,*,*,*,*,*,お,オ,オ
EOS
------

**Comment by polm** [comment]
The `mecab` you use on the command line is the mecab binary program, not the Python wrapper (this package). Try this:

     pip install mecab-python3

**Comment by foxonspace** [comment]
I did try that before, it does not work

[root@Chatbot sh]# pip install mecab-python3
Requirement already satisfied: mecab-python3 in /usr/lib64/python3.5/site-packages (1.0.0)

**Comment by polm** [comment]
If you are getting `ModuleNotFoundError` then it's possible that your shell script is using a different Python version or a virtual environment or something, which means it's looking for mecab-python3 in a different place. If you can share your code I can try to help with that, but it's a problem that doesn't have anything to do with this package.

**Comment by polm** [comment]
If you can get to where you have a RuntimeError again, please install version 1.0.1. I have updated the error output so it's easier to understand what's going on.

**Comment by polm** [comment]
Closing this due to lack of reply, but if you are still having trouble let me know and I can try to help.
