### ISSUE TITLE
Azure FunctionでRuntime error発生

### ISSUE THREAD

**Issue by yuanweilei** [SamuraiT/mecab-python3#52]
お世話になります。

【Issue】
7/21時点、ローカルでは問題ありませんでしたが、
mecab-python3を利用したAzure FunctionをAzureにデプロイして実行したところ、下記のエラーが発生しました。
```
Exception while executing function: Functions.getkeywords Result: Failure
Exception: RuntimeError: 
Stack:   File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 343, in _handle__invocation_request
    call_result = await self._loop.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 480, in __run_sync_func
    return func(**params)
  File "/home/site/wwwroot/getkeywords/__init__.py", line 27, in main
    mecab = MeCab.Tagger()
  File "/home/site/wwwroot/.python_packages/lib/site-packages/MeCab/__init__.py", line 124, in __init__
    super(Tagger, self).__init__(args)
```

【環境】
python 3.8

【ソースコード】

```
import logging
import os
import azure.functions as func
import MeCab
import sys
import re
from collections import Counter

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    text = req.params.get('text')
    if not fullText:
        try:
            req_body = req.get_json()
        except ValueError:
            pass
        else:
            fulltextext = req_body.get('text')

    if text:
         # MeCabを使用してテキストを形態素解析
        mecab = MeCab.Tagger()
        parse = mecab.parse(text)
```

【requirements.txt】
azure-functions
mecab-python3

Azure サービス側の問題なのか、mecab-python3の問題なのか分からないですが、
一旦ここで質問させてください。

**Comment by polm** [comment]
ご報告ありがとうございます。

下記を見ると、おそらくmecab-python3のエラーです。

> Exception: RuntimeError: 

MeCab本家のバグで、`MeCab.Tagger()`で`RuntimeError`になってもエラーメッセージが出ないことがあります。

mecab-python3のバージョンはなんですか？v1.0.1ならERROR DETAILSのところにもっと詳しいエラーメッセージが出ると思います。お手数ですが、可能ならv1.0.1に更新して再実行をお願いします。

**Comment by yuanweilei** [comment]
ご回答ありがとうございます。
バージョン未指定でしたのでビルド時に最新のバージョン(v1.0.1のはず）を使うと思います。

mecab-python3 == 0.996.5に設定したところ解決しました。
本件はCloseをお願いします。

**Comment by polm** [comment]
なるほど、情報ありがとうございます。解決できてよかったです。

0.996.5で解決したということはおそらく辞書がなかったんです。0.996.5版でipadicは付いていますけど、1.0から別途辞書をインストールする必要があります。

https://github.com/polm/ipadic-py

**Comment by yuanweilei** [comment]
はい、neologd辞書とカスタマイズ辞書を使う予定なので、MeCab.Tagger()に-d -uで指定しています。

1.0を使いたかれば、import ipadicを追記するだけですよね？
試してみます。

**Comment by polm** [comment]
> はい、neologd辞書とカスタマイズ辞書を使う予定なので、MeCab.Tagger()に-d -uで指定しています。

なるほど、そういうことですね。サンプルコードに`Tagger()`だけとなったので辞書がないと思いました。

辞書が別にあるならipadic-pyを入れる必要はありませんが、mecabrcを指定する必要があります。

    mecab = MeCab.Tagger('-u /hoge/hoge.dic -d /hoge/neologd -r /hoge/mecabrc')

mecabrcは内容がなくてもいいですが、全く指定しないとmecabが動きません。0.996.5以前だとipadicと一緒に付いていました。

**Comment by yuanweilei** [comment]
ありがとうございます。初心者レベルの質問ですが、
mecabrcは空のファイルを作って、mecabrcというファイル名にすればいいでしょうか？

**Comment by polm** [comment]
ファイルがない場合新しく作らなくてもいいです。 Linux系OSで`-r /dev/null`を指定すれば大丈夫です。
