### ISSUE TITLE
WindowsにおけるMeCab使用時のErrorについて

### ISSUE THREAD

**Issue by shirotoo** [SamuraiT/mecab-python3#54]
当方、初めて質問をさせていただきます。めっきりの初心者故、至らない点があるかもしれませんが、その際はご教示くだされば幸いです。

windows10でMeCabを使用したいと思い、Anaconda、Python、MeCabをインストールいたしました。
MeCabのimportにも成功したため、

```
m = MeCab.Tagger ("-Ochasen")

を入力したしましたら、以下のエラーが表示されました。

----------------------------------------------------------


Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/SamuraiT/mecab-python3#common-issues

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/SamuraiT/mecab-python3/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: -Ochasen
error message:  [!tmp.empty()] unknown format type [chasen]

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-133a51a3f9e9> in <module>
----> 1 m = MeCab.Tagger ("-Ochasen")

~\anaconda3\envs\MeCab\lib\site-packages\MeCab\__init__.py in __init__(self, rawargs)
    122 
    123         try:
--> 124             super(Tagger, self).__init__(args)
    125         except RuntimeError:
    126             error_info(rawargs)

RuntimeError: 

-----------------------------------------------------------------------------------------
```

URLにもアクセスをし、問題解決を図ろうと思いましたが、私一人の力では解決できませんでした。そこで、お力をお借りしたいです。

スペックは
python3.8.2
anaconda3
MeCab(32bit) →　64bit版も試行済み
です。

また、こちらのWebサイトを参考に処理を行いました。
https://techacademy.jp/magazine/22052

助太刀いただければ幸いです。
以上、よろしくお願いいたします。

**Comment by polm** [comment]
ご報告ありがとうございます、エラーが分かりにくくてすみません。

エラーの原因は後で説明しますが、まず解決法から説明すると、こうすればchasen出力フォーマットは使えます。まずipadicをインストールしてください。

    pip install ipadic

で、こうします。

```
import MeCab
import ipadic

CHASEN_ARGS = r' -F "%m\t%f[7]\t%f[6]\t%F-[0,1,2,3]\t%f[4]\t%f[5]\n"'
CHASEN_ARGS += r' -U "%m\t%m\t%m\t%F-[0,1,2,3]\t\t\n"'
tagger = MeCab.Tagger(ipadic.MECAB_ARGS + CHASEN_ARGS)

print(tagger.parse("図書館にいた事がバレた"))
```

出力はこうなるはずです。

```
図書館  トショカン      図書館  名詞-一般
に      ニ      に      助詞-格助詞-一般
いた事  イタコト        いた事  名詞-一般
が      ガ      が      助詞-格助詞-一般
バレ    バレ    バレる  動詞-自立       一段    連用形
た      タ      た      助動詞  特殊・タ        基本形
EOS
```

これでうまく動かなかったら教えてください。

それでエラーの原因ですが、現在の環境でchasenの出力フォーマットが定義されてないことが原因です。chasenの出力フォーマットはMeCabの基本機能ではなくて、ipadicという辞書のdicrc（設定ファイル）で定義されていることが多いです。[MeCab本家のdicrc](https://github.com/taku910/mecab/blob/master/mecab-ipadic/dicrc)の出力フォーマットを以上の`CHASEN_ARGS`で指定しています。出力フォーマットの詳細については[MeCabの資料](https://taku910.github.io/mecab/#format)を参照してください。

他になにかご不明な点とかありましたらお気軽に教えてください。

**Comment by shirotoo** [comment]
ご返信ありがとうございます。
無事出力されました。
ここで、もう一つお伺いしたいのですが、例えば、MeCabから動詞のみ抽出する際はどのようなプログラムを行えばよいでしょうか。

https://fresopiya.com/2019/04/09/mecabhinshi/

こちらを参考に行ってみましたが、エラーを吐き出しました。
以下、エラーを記述します。

----------------------------------------------------------

Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/SamuraiT/mecab-python3#common-issues

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/SamuraiT/mecab-python3/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: -d /usr/local/lib/mecab/dic/mecab-ipadic-neologd
error message: [ifs] no such file or directory:
/usr/local/lib/mecab/dic/mecab-ipadic-neologd\dicrc

---------------------------------------------------------------------------RuntimeError
                             Traceback (most recent call
last)<ipython-input-10-3be3502b7d4a> in <module>      3 CHASEN_ARGS =
r' -F "%m\t%f[7]\t%f[6]\t%F-[0,1,2,3]\t%f[4]\t%f[5]\n"'      4
CHASEN_ARGS += r' -U "%m\t%m\t%m\t%F-[0,1,2,3]\t\t\n"'----> 5 mecab =
MeCab.Tagger ('-d /usr/local/lib/mecab/dic/mecab-ipadic-neologd')
6 text = input("解析する文章を入力してください：")      7 result = mecab.parse(text)
~\anaconda3\envs\MeCab\lib\site-packages\MeCab\__init__.py in
__init__(self, rawargs)    122     123         try:--> 124
super(Tagger, self).__init__(args)    125         except RuntimeError:
   126             error_info(rawargs*)*以上、よろしくお願いいたします*。
*




2020年7月30日(木) 19:13 polm <notifications@github.com>:

**Comment by polm** [comment]
今回のエラーはこれですね。

> error message: [ifs] no such file or directory: /usr/local/lib/mecab/dic/mecab-ipadic-neologd\dicrc

neologdの設定ファイルが見つからないとのことです。Neologdは別の辞書で、使うのであれば別途インストールする必要があります。ファイルサイズが大変大きいのでpip経由ではインストールできません。しかしneologdがなくてもMeCabは普通に使えますので今回インストールする必要はありません。それで今回前回紹介したipadicを引き続き使っていきます。

```
import MeCab
import ipadic

tagger = MeCab.Tagger(ipadic.MECAB_ARGS)

node = tagger.parseToNode("ネギが落ちている。誰が落としたんだろう。")
node = node.next # 最初のnodeを飛ばす
while node.next:
    # surface = 表層、入力文そのまま
    surface = node.surface
    # feature は詳細情報、形式はカンマ区切り
    # 例: 落ち-> 動詞,自立,*,*,一段,連用形,落ちる,オチ,オチ
    # 1番目のフィールドが基本品詞
    hinshi = node.feature.split(',')[0]
    # 今回分かち処理を確認できるようにあえて全部printする
    if hinshi == "動詞":
        print("動詞", surface, sep="\t")
    else:
        print(" ", surface, sep="\t")
    node = node.next
```

それで出力はこうなります。

```
        ネギ
        が
動詞    落ち
        て
動詞    いる
        。
        誰
        が
動詞    落とし
        た
        ん
        だろ
        う
        。
```

これで動詞を見分けることができますがいかがでしょうか。

**Comment by shirotoo** [comment]
無事出力することができました。
ご丁寧にありがとうございました。
