### ISSUE TITLE
error message: [ifs] no such file or directory: c:\mecab\mecabrc

### ISSUE THREAD

**Issue by holly7777** [SamuraiT/mecab-python3#55]
Mecabをインストールして、インポートしたが、以下のエラーがでる

Mecabはコマンドライン上では動く
pip install ipykernel
pip install mecab-python-windows
もインストール済
(MeCabのインストール先)/binにある"libmecab.dll"というファイルを
(Pyhthonのインストール先)/Lib/site-packagesにコピペ済

```
------------------- ERROR DETAILS ------------------------
arguments: -Ochasen
error message: [ifs] no such file or directory: c:\mecab\mecabrc
----------------------------------------------------------
```

**Comment by polm** [comment]
おそらく辞書はインストールされていません。`pip install unidic-lite`を実行して、`-Ochasen`を使わなければ動くと思います。

他の注意点として、

1. コマンドラインでうごくmecabとmecab-python3は普段連携しないので無関係です。
2. mecab-python-windowsはmecab-python3とは別物です、両方を同時に入れるとどう動作するか分かりません。どちらか片方をuninstallしてください。
3. mecab-python-windowsはおそらくメンテされていません。`pip install mecab`で最新版をインストールできると思います。
4. mecab-python3を使う場合dllをコピーする必要はありません。

**Comment by polm** [comment]
返事がないのでクローズしますがまだ解決してないなら教えてください。

**Comment by whaozl** [comment]
right method as follows:
in cnetos7:
1、please make  mecab-0.996.tar.gz
and configure PATH variable:
export PATH=/usr/local/mecab/bin:$PATH
2、install mecab-ipadic-2.7.0-20070801.tar.gz
3、install https://github.com/neologd/mecab-ipadic-neologd.git
4、pip3 install mecab-python3
5、test this is ok

in win10:
1、install [mecab-0.996.exe](https://drive.google.com/drive/folders/0B4y35FiV1wh7fjQ5SkJETEJEYzlqcUY4WUlpZmR4dDlJMWI5ZUlXN2xZN2s2b0pqT3hMbTQ?resourcekey=0-VaHzcd_V8qgKt66qJDufGw) to c:\mecab
2、configure  add system PATH variable:  c:\Mecab\bin
3、pip3 install mecab-python3
4、cp on centos7 dict (/usr/local/mecab/lib/mecab/dic/neologd) to c:\Mecab\dic directory.
5、test this.

**Comment by polm** [comment]
@whaozl Your comment has nothing to do with the issue here. If you have a question could you open a new issue?
