### ISSUE TITLE
No dicrc with neologd

### ISSUE THREAD

**Issue by Srishtisawla** [SamuraiT/mecab-python3#56]
I am using mecab-python3 in Mac

 
```
------------------- ERROR DETAILS ------------------------ 
arguments: -d /usr/lib/x86_64-linux-gnu/mecab/dic/mecab-ipadic-neologd 
error message: [ifs] no such file or directory: /usr/lib/x86_64-linux-gnu/mecab/dic/mecab-ipadic-neologd/dicrc #56
```

**Comment by polm** [comment]
You don't have a dicrc. You need to get one, I'm not entirely sure where the dicrc for using neologd as a system dictionary should come from, you can try asking at their repository.

https://github.com/neologd/mecab-ipadic-neologd

If you are new to using mecab, I strongly suggest you avoid using neologd until you have experience using other dictionaries. If you install `unidic-lite` and don't use the `-d` flag for neologd MeCab should just work.

**Comment by polm** [comment]
Note it's possible the dictionary also just doesn't exist. Did you install neologd? Does the directory below exist?

    /usr/lib/x86_64-linux-gnu/mecab/dic/mecab-ipadic-neologd

**Comment by polm** [comment]
Closing due to lack of response, but please feel free to reopen if you're still having trouble.
