### ISSUE TITLE
Binary package for Python 3.9

### ISSUE THREAD

**Issue by noritada** [SamuraiT/mecab-python3#57]
Hi,

Thank you very much for providing a useful package.

Since Python 3.9 was released on 2 weeks ago, Oct. 5, 2020, it would be nice if this package can have a binary package for Python 3.9. Do you have a plan to make a new release in the near future? It seems that cibuildwheel already supports 3.9 and I think the next release will automatically have a package for that version.

Since `pip install` tries to run `setup.py bdist_wheel` in 3.9 environments as of now, if there is a new release in the near future, I'd like to wait.

Sorry for just asking a question.
Many thanks!

**Comment by polm** [comment]
Thanks for the heads up. It hadn't occurred to me that I'd need to update the wheel building for 3.9, but it shouldn't be hard - I'll do a new release with that soon.

**Comment by noritada** [comment]
Thank you very much for your comments! It is very helpful for me.

**Comment by polm** [comment]
I've uploaded wheels for `v1.0.2a3` to pypi, could you check that they work for you?

    pip install mecab-python3==1.0.2a3

If that's OK I can make it a proper release.

Getting the builds working was a little trickier than expected as Travis seemed to pull down an old version of cibuildwheel for the first few builds, but it seems to be working fine now.

**Comment by noritada** [comment]
Thank you very much for your releasing and dealing with Travis' behavior. I appreciate it.

Now I can successfully install the wheel of that version.

```
%  pip3 install mecab-python3=="1.0.2a3"
Collecting mecab-python3==1.0.2a3
  Downloading mecab_python3-1.0.2a3-cp39-cp39-macosx_10_9_x86_64.whl (302 kB)
     |████████████████████████████████| 302 kB 4.4 MB/s 
Installing collected packages: mecab-python3
Successfully installed mecab-python3-1.0.2a3
```

So, I should close this issue.
Many thanks!

**Comment by polm** [comment]
Thanks for the confirmation! Since it's kind of late today I'll make the release tomorrow morning.
