### ISSUE TITLE
Runtime error in in the version 1.0.2

### ISSUE THREAD

**Issue by prashant-bansod** [SamuraiT/mecab-python3#59]
Hi! I am getting this error on Windows 10.
Python version - 3.6

The default output parameter works fine but the other parameters like "Ochasen" do not work.
Could you please help me in figuring it out?
Thanks.

`m = MeCab.Tagger("-Ochasen")`

```
------------------ ERROR DETAILS ------------------------
arguments: -Ochasen
error message:  [!tmp.empty()] unknown format type [chasen]
----------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ts-prashant.bansod\Python\Python36\lib\site-packages\MeCab\__init__.py", line 124, in __init__
    super(Tagger, self).__init__(args)
RuntimeError


```

**Comment by polm** [comment]
This is covered in [the FAQ][faq], but `-Ochasen` is not a built in feature of MeCab, it is a feature of the IPAdic dictionary. You can use it if you install IPAdic and it's in the `dicrc`. 

That said, there's no reason to use `-Ochasen` unless you need compatibility with old code. It's just an output format.

[faq]: https://github.com/SamuraiT/mecab-python3#using-unsupported-output-modes-like--ochasen

**Comment by polm** [comment]
Closing due to lack of response, but if you are still having trouble feel free to reopen this.
