### ISSUE TITLE
Can I build user dictionary at Windows?

### ISSUE THREAD

**Issue by ymd-h** [SamuraiT/mecab-python3#64]
Hi, developers.

Can I build user dictionary without installing additional MeCab build?

I couldn't find `mecab-dict-index.exe` at the installation folder. (Does the `libmecab.dll` contain the functionality?)

I installed from PyPI with pip.

* Windows 10
* python 3.8.8
* mecab-python3 1.0.3

**Comment by polm** [comment]
The tools for building a user dictionary are not distributed with mecab-python3 - they weren't when I took over maintenance and I've never added them. 

I recently added the dictionary building command to [fugashi](https://github.com/polm/fugashi) as an experimental feature, so you could try that if you like. 

While I'd like to make things as easy to use as possible, adding an interface to the dictionary builder is something I've only recently started working on, so if you're at the point where you need to build a user dictionary you should probably get familiar enough with raw MeCab to install it yourself. 

> Does the libmecab.dll contain the functionality?

The functionality is technically in the DLL but there's no access to it in mecab-python3.

**Comment by ymd-h** [comment]
@polm 

Thank you for your reply.

I understand the situation. I will look fugashi as you suggested.
