### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by inspiralpatterns** [SamuraiT/mecab-python3#7]
Here is the error code resulting from `pip install mecab-python3`:

```
Complete output from command python setup.py egg_info:
    sh: 1: mecab-config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-csKl_P/mecab-python3/setup.py", line 41, in <module>
        include_dirs=cmd2("mecab-config --inc-dir"),
      File "/tmp/pip-install-csKl_P/mecab-python3/setup.py", line 27, in cmd2
        return string.split(cmd1(strings))
      File "/tmp/pip-install-csKl_P/mecab-python3/setup.py", line 24, in cmd1
        return os.popen(strings).readlines()[0][:-1]
    IndexError: list index out of range
```

does anyone have an explanation for this?
I am running this inside Docker, `python -- version 2.7.14` and `pip --version 10.0.1`

**Comment by himkt** [comment]
I have the same problem.
In my case, I forgot to install MeCab (make sure if you successfully installed MeCab!).

**Comment by inspiralpatterns** [comment]
Same here.
I will close the issue.

**Comment by jini20** [comment]
I have the same issue.. 

(venv)git clone https://bitbucket.org/eunjeon/mecab-python-0.996.git
(venv)cd mecab-python-0.996/
(venv)python3 setup.py build  -> this phase cause the problem!!
(venv)python3 setup.py install

I'm trying to install mecab now!!!  
Could anyone help me ?

**Comment by zackw** [comment]
@jini20 Do you have the MeCab library installed?  The package does not include the library itself, only the Python wrapper.
