### ISSUE TITLE
Trouble installing on Mac OS Sierra

### ISSUE THREAD

**Issue by JTesch17** [SamuraiT/mecab-python3#70]
Terminal Output:

ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xg/m49yvbf50wzd2kw0v0lqnkpw0000gn/T/pip-install-m7yaio8q/mecab-python3_fef3e8a008cd4211a9358e3d5ff6a04c/setup.py'"'"'; __file__='"'"'/private/var/folders/xg/m49yvbf50wzd2kw0v0lqnkpw0000gn/T/pip-install-m7yaio8q/mecab-python3_fef3e8a008cd4211a9358e3d5ff6a04c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xg/m49yvbf50wzd2kw0v0lqnkpw0000gn/T/pip-record-59irjqme/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/mecab-python3
         cwd: /private/var/folders/xg/m49yvbf50wzd2kw0v0lqnkpw0000gn/T/pip-install-m7yaio8q/mecab-python3_fef3e8a008cd4211a9358e3d5ff6a04c/
    Complete output (11 lines):
    WARNING: The wheel package is not available.
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/MeCab
    copying src/MeCab/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/MeCab
    copying src/MeCab/cli.py -> build/lib.macosx-10.9-x86_64-3.7/MeCab
    running build_ext
    error: [Errno 2] No such file or directory: 'mecab-config': 'mecab-config'

**Comment by JTesch17** [comment]
Complete output (10 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/MeCab
    copying src/MeCab/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/MeCab
    copying src/MeCab/cli.py -> build/lib.macosx-10.9-x86_64-3.7/MeCab
    running build_ext
    error: [Errno 2] No such file or directory: 'mecab-config': 'mecab-config'

**Comment by JTesch17** [comment]
Got it to work just had to manually install mecab using the japanese instructions... and reinstall fugashi ... .. all this just to use cutlet.... so that i'll... be able to read said instructions.. ... . .. . .

**Comment by polm** [comment]
Uh, sorry you had trouble with this. I'm kind of confused about what you were trying to do here, but some points:

1. It looks like you were trying to build from source rather than install a wheel. When installing from source you have to install MeCab yourself. On OSX you should be able to use the wheels and so you shouldn't have to install MeCab. If the wheels didn't work for some reason that may be an issue I can fix.
2. mecab-python3, fugashi, and cutlet are all maintained by me, but they are separate packages. I do not understand which one you were actually trying to use.

**Comment by JTesch17** [comment]
Thanks for the response. I really admire people like you. 

So: I was trying to use cutlet to parse an Anki deck with python to add romanized on/kun readings to the answer field for all joyo kanji.. Anyway, after using pip to install cutlet, i was getting errors about various missing mecab files (namely mecab-config, and mecab-dict-index), despite having followed cutlet's github guide and installing unidic lite. So I spent a few hours troubleshooting/moving files/installing packages and just ended up following the command line protocol on the japanese guide made by taku910.

The wheel wasn't working for me, but I also hadn't updated xcode/it wasn't opening due to some old certificate... After fixing that though, I was still unable to install mecab or mecab-python3 via pip so I just had to run the command line :
>>tar zxfv mecab-0.996.tar.gz
>>cd mecab-0.996
>>./configure 
>>make
>>su make install

All errors occurred when trying to call katsu.romaji() in my python program. 

After this there was still some issue with fugashi, but after using pip to uninstall/reinstall, everything finally worked. Learned 110 kanji yesterday 

一二三四五六七八九十口上下川山水氷百万足目耳打花平気早仕写央車竹冬広用止引公分外元古今北午母台生内心半毛友少父太戸方切牛市矢円文白木千刀日丁立小才右王天手火了出夕犬土正丸子本玉又女力人入工大虫字男主名不号他去皿

with all the readings thanks to cutlet and am looking to do the same today !<∂-Ō∆Ō>!

**Comment by polm** [comment]
Huh, that sounds weird - sorry it gave you trouble, but glad you got it working - good luck with your learning!
