### ISSUE TITLE
miniforgeの仮想環境でImport Errorが発生する

### ISSUE THREAD

**Issue by XdekcE** [SamuraiT/mecab-python3#72]
こんにちは。conda-forgeのcondaインストーラーである[miniforge](https://github.com/conda-forge/miniforge)で構築した仮想環境で
MeCabをImportしようすると、Import Errorが発生します。

実行環境とエラーの内容は次の通りです。

**実行環境**
- macOS Big Sur 11.5.2 Macbook Air (Apple M1) 
- conda 4.10.3
- pip 21.2.4
- Python 3.8.10 (packaged by conda-forge)
- mecab-python3 1.0.4

**出力されたエラー**
```
>>> import MeCab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/USER_NAME/miniforge3/envs/tf/lib/python3.8/site-packages/MeCab/__init__.py", line 10, in <module>
    from . import _MeCab
ImportError: dlopen(/Users/USER_NAME/miniforge3/envs/tf/lib/python3.8/site-packages/MeCab/_MeCab.cpython-38-darwin.so, 2): Symbol not found: __ZN5MeCab11createModelEPKc
  Referenced from: /Users/USER_NAME/miniforge3/envs/tf/lib/python3.8/site-packages/MeCab/_MeCab.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/USER_NAME/miniforge3/envs/tf/lib/python3.8/site-packages/MeCab/_MeCab.cpython-38-darwin.so
```

上記のエラーはminiforgeで構築した仮想環境で発生し、anacondaで構築した仮想環境では正常に動作します。

同様のエラーが出ている方の[解決策](https://qiita.com/G1998G/items/2ad1b62c0285e478bfab)を試してみましたが、解決できなかったため、ここで質問させていただきました。
よろしくお願いします。

**Comment by polm** [comment]
ご報告ありがとうございます。

Macを使っていないのでこちらで確認はできませんが、少し調べたところ、pythonとmecab-python3のアーキテクチャが違うのかもしれません。mecab-python3はOSXでx86_64版しかないので、もしminicondaのPythonがarm64であればこのようなエラーが出るみたいです。 

https://github.com/mrjbq7/ta-lib/issues/408

このコマンドでPythonのアーキテクチャを確認できますがどうなっていますか。

    file miniconda/bin/python

アーキテクチャ違いが原因でしたら、Pythonをx86_64版に変更すると解決するはずです。

もしそれで解決できなかったら教えてください、他なにか考えられる原因がないか調べてみます。

**Comment by XdekcE** [comment]
@polm 
ご返答ありがとうございます。
Pythonアーキテクチャ確認してみたところ、arm64版でしたので、arm64からx86_64に変更し、再度Importしたところ正常に動作しました。有難うございました。
