### ISSUE TITLE
えーとmecabがあるファイルを指定できるようにしてほしい

### ISSUE THREAD

**Issue by tuna2134** [SamuraiT/mecab-python3#78]

**Comment by polm** [comment]
どういうことでしょうか。すみませんがタイトルだけでは意味が分かりません。

**Comment by polm** [comment]
なるほど。

mecab-python3を使うためにMeCabを別途インストールする必要はありません。また、普通にmecab-python3をインストールする場合、別途インストールされたMeCabのバイナリはそもそも利用されません。

今の問題はおそらく辞書がインストールされてないことが原因です。`pip install unidic-lite`で直ると思います。

既存のmecabrc/辞書を使いたい場合、MeCabと同様 `-r` や `-d` で指定できます。

```
import MeCab

tagger = MeCab.Tagger("-r hoge/hoge/mecabrc -d piyo/piyodic")
```

**Comment by tuna2134** [comment]
なるほど
試してみます

**Comment by tuna2134** [comment]
いけました！
