### ISSUE TITLE
MeCab使用問題

### ISSUE THREAD

**Issue by Fllz** [SamuraiT/mecab-python3#79]
おはようございます！
李と申します。MeCabをインストール完了致しました。しかし、Runtime errorが発生しました。内容は[arguments: -Owakati
[ifs] no such file or directory: D:\Anaconda3\lib\site-packages\unidic\dicdir\mecabrc]。お手数ですが、解決方法をお教えていただけますでしょうか。よろしくお願いいたします。

**Comment by polm** [comment]
`mecabrc`が見つからない系のエラーは主に辞書がインストールされていないときに起きてしまいます。下記のコマンドで辞書をインストールすると直ると思います。

    pip install unidic-lite

もしそれで直らなかったら教えてください。

**Comment by Fllz** [comment]
ありがとうございました！
こちらが解決致しました。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SamuraiT/mecab-python3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月17日(星期四) 中午12:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SamuraiT/mecab-python3] MeCab使用問題 (Issue #79)





 
mecabrcが見つからない系のエラーは主に辞書がインストールされていないときに起きてしまいます。下記のコマンドで辞書をインストールすると直ると思います。
 pip install unidic-lite  
もしそれで直らなかったら教えてください。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
