### ISSUE TITLE
Encountered error while trying to install package

### ISSUE THREAD

**Issue by zoldaten** [SamuraiT/mecab-python3#80]
Hi!
Trying to build a package from source on Raspberry pi4b buster -
Linux ROBIN 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

but crashed:
```
Running setup.py install for mecab-python3 ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for mecab-python3 did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-3.7
      creating build/lib.linux-armv7l-3.7/MeCab
      copying src/MeCab/cli.py -> build/lib.linux-armv7l-3.7/MeCab
      copying src/MeCab/__init__.py -> build/lib.linux-armv7l-3.7/MeCab
      running build_ext
      error: [Errno 2] No such file or directory: 'mecab-config': 'mecab-config'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> mecab-python3

note: This is an issue with the package mentioned above, not pip.
```
also it is not working with pip install...

could you help ?

**Comment by polm** [comment]
To build from source you need to install Mecab first and have `mecab-config` in your path.

**Comment by polm** [comment]
Closing due to lack of response, but if you are still having trouble please feel free to follow up.

**Comment by zhanganna06** [comment]
Hi,
I have installed mecab with homebrew but still got the same error when building from source.
My env is Apple M2 Ventura 13.4 and I can find mecab-config:
```
/opt/homebrew/Cellar/mecab/0.996/bin/mecab-config
```
How can I set the proper path when building?
Thanks!

**Comment by FlashlightET** [comment]
im getting this too and im not even trying to build from source im just running `pip install mecab-python3`

**Comment by polm** [comment]
Pip will automatically try to build from source if a wheel is not available for your platform. For the original user here, it's probably because they're using a Raspberry Pi. Perhaps you're using some unusual hardware or Python 3.12, which doesn't have wheels yet?

**Comment by polm** [comment]
See #100.
