### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by sanket9823** [SamuraiT/mecab-python3#82]
------------------- ERROR DETAILS ------------------------
arguments: -Owakati
[ifs] no such file or directory: /usr/local/etc/mecabrc
----------------------------------------------------------

**Comment by polm** [comment]
Hey, please don't just post an error message, please explain what you were trying to do.

In this case you probably need to read the README. It sounds like you didn't install a dictionary.

**Comment by polm** [comment]
Closed due to lack of reply.
