### ISSUE TITLE
[tokenizer_->open(param)] tokenizer.cpp(130) [sysdic->isCompatible(*d)] incompatible dictionary

### ISSUE THREAD

**Issue by yuta1371** [SamuraiT/mecab-python3#92]
```
RuntimeError: 
------------------- ERROR DETAILS ------------------------
arguments: -u C:/Users/xxxx/MeCab/dic/ipadic/test.dic
) [tokenizer_->open(param)] tokenizer.cpp(130) [sysdic->isCompatible(*d)] incompatible dictionary: C:/Users/xxxx/MeCab/dic/ipadic/test.dic 
----------------------------------------------------------

mecab = MeCab.Tagger('-d C:/Users/xxxx/MeCab/dic/ipadic')
mecab = MeCab.Tagger('-u C:/Users/xxxx/MeCab/dic/ipadic/test.dic') 　 ← ERROR
```

Python                        3.9.13
mecab-python3          1.0.6
unidic-lite                   1.0.8

mecabrcに以下を追加
userdic = C:/Users/xxxx/MeCab/dic/ipadic/test.dic
dicrcに以下を追加
userdic = C:/Users/xxxx/MeCab/dic/ipadic/test.dic

初心者です。
ユーザー辞書を追加して、コマンドプロンプトで追加した辞書が反映されているのを確認後、Pythonで実行しました。
上記のようなエラーが出てます。エラー箇所をコメントアウトすると、実行可能ですが、当然ですが追加したユーザー辞書は反映されません。通常のデフォルト辞書でのmecab実行はできています。

以上、ご助言をよろしくお願いします。

**Comment by polm** [comment]
ご報告と細かい情報ありがとうございます。この辺の設定が難しくてすみません。

引数を別々で指定すると、両方が採用されるわけではなく、変数の値が上書きされるだけなので、同時に指定する必要があります。以下のコードで正しく動作すると思います。

```
mecab = MeCab.Tagger('-d C:/Users/xxxx/MeCab/dic/ipadic -u C:/Users/xxxx/MeCab/dic/ipadic/test.dic') 
```

また、コマンドプロンプトから動作を確認したとのことですが、mecab-python3はmecabのバイナリを内蔵しているので、システムのmecabとは基本的に無関係です。（言い換えれば、別途mecabをインストールしなくても普通に動作します。）mecab-python3の動作はmecab-pyでコマンドプロンプトから確認できます。

**Comment by yuta1371** [comment]
ご助言通りに実行すると、エラーなく出来ましたが、ユーザー辞書が反映されていませんでした。辞書の作り方が間違っていますか？ちなみにC:/Users/xxxx/MeCab/dic/ipadicからtest.dicを削除すると、辞書がないってエラーが出ています。

以下、辞書の作り方

メモ帳に「メロンパン,1285,1285,4000,名詞,一般,*,*,*,*,メロンパン,メロンパン,メロンパン」と書いて、
文字コード：UTF-8、ファイル名：test.csvでC:/Users/xxxx/MeCab/dic/ipadicに保存。

その後、コマンドプロンプトで「cd C:/Users/xxxx/MeCab/dic/ipadic」、
「mecab-dict-index -f utf-8 -t utf-8 -d "C:/Users/xxxx/MeCab/dic/ipadic" -u test.dic test.csv」を実行して、test.dicを作成。

・Python実行で欲しい結果
メロンパン   名詞,一般,*,*,*,*,メロンパン,メロンパン,メロンパン

・実際の結果
名詞,普通名詞,一般,*,*,*,メロン,メロン-melon,メロン,メロン,メロン,メロン,外,*,*,*,*,メロン,メロン,メロン,メロン,*,*,1,C1,*
名詞,普通名詞,一般,*,*,*,パン,パン-pao,パン,パン,パン,パン,外,*,*,*,*,パン,パン,パン,パン,*,*,1,C3,*

ユーザー辞書が反映されていないのかと判断しましたが、おかしな点はありますでしょうか？

以上、よろしくお願いします。

**Comment by polm** [comment]
こちらで試してみたんですが、「メロンパン」が1語として出ました。

出力の形式が少しおかしいです。`外`や`C3`みたいな情報はIPADicにはないので、UniDicを参照しているみたいです。実際実行しているコードはどうなっていますか？

あと、Markdown でコードやCSVの内容を記述してください、そうしないと読みづらいです。

https://docs.github.com/ja/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

こちらで使ったコードは以下の通りです。

```
import MeCab
tagger = MeCab.Tagger("-d /usr/local/lib/mecab/dic/ipadic -u test.dic")
tagger.parse("メロンパン")
# 出力 => 'メロンパン\t名詞,一般,,,,,メロンパン,メロンパン,メロンパン\nEOS\n'
```

**Comment by yuta1371** [comment]
確認したところ、解決しました。
おっしゃる通り、以下の２行目を消し忘れていました。凡ミスですみません、、、

```
mecab = MeCab.Tagger('-d C:/Users/xxxx/MeCab/dic/ipadic -u C:/Users/xxxx/MeCab/dic/ipadic/test.dic') 
mecab = MeCab.Tagger()
```

以上、ありがとうございました。

**Comment by polm** [comment]
解決できてなによりです。
