### ISSUE TITLE
no such file or directory: mecabrc

### ISSUE THREAD

**Issue by suzuey** [SamuraiT/mecab-python3#93]
------------------- ERROR DETAILS ------------------------
arguments: -Owakati
[ifs] no such file or directory: C:\Users\wusea\AppData\Local\Programs\Python\Python311\Lib\site-packages\unidic\dicdir\mecabrc

I have no clue how to fix this, even after I've read the README file attached with the error. Would appreciate it if someone could explain the process to me

**Comment by polm** [comment]
It looks like you're using the full UniDic but the mecabrc isn't found. Did you run the additional download step? 

```
python -m unidic download
```

If you hadn't run the step, that would explain this error. If you did download it and are still getting this error, please tell me what the contents of the `dicdir` are.

**Comment by polm** [comment]
Closing for lack of reply.
