### ISSUE TITLE
Failed initializing MeCab.

### ISSUE THREAD

**Issue by Yoshihiro-Gocho** [SamuraiT/mecab-python3#94]
arguments: -r /dev/null -d /usr/local/lib/mecab/dic/mydic
[ifs] no such file or directory: /usr/local/lib/mecab/dic/mydic/dicrc

**Comment by polm** [comment]
It looks like you're trying to use a custom system dictionary but have no dicrc file. System dictionaries require a dicrc file - for an example, see the ones included with UniDic or other dictionaries. 

Also, when posting issues, please don't just post the error message, explain what you were actually trying to do, as that's necessary context for resolving the issue.

Closing due to lack of detail, but feel free to follow up.

**Comment by Yoshihiro-Gocho** [comment]
First of all, thank you for your reply. Also, I apologize for the inconvenience caused.
I will explain the situation again.
Using Google Colaboratory, when I was trying to use MeCab, I got the error you posted. It would be helpful if you could tell me the specific procedure to create a dicrc file on Google Colaboratory.

**Comment by polm** [comment]
Thank you for following up, but unfortunately your details are not very helpful.

It is good to know you were using Google Colaboratory. But what were you trying to do? Can you include code? Why did you use those arguments, and did you actually intend to make a custom *system* dictionary? That's an advanced task and usually not necessary, and it's more common to make a custom user dictionary. However, if you just want to use MeCab then you don't need a custom dictionary at all.

If you are making a system dictionary, as I mentioned, you can refer to the ones included with UniDic or IPAdic as examples. They're short files, and it should be easy to copy and edit them. If you are confused by their contents, please be specific about what you didn't understand.

**Comment by polm** [comment]
Thank you for the more detailed explanation. 

First, I am not a company, I am an individual who does this in my spare time. Nobody pays me for this. This is often the case with open source software.

Second, please be very careful about asking ChatGPT for advice, as it will make stuff up that makes no sense. In this case it has reasonably suggested you restarted the runtime and be sure that the dictionary exists, but it can also make nonsense suggestions.

Now, regarding your specific issue, it looks like there are a few issues with the guide you are using. You should be able to use this code in Colab to run MeCab in Python:

```
!pip install mecab-python3 unidic-lite
import MeCab
text = 'これは日本語の文章です。'
tagger = MeCab.Tagger("-Owakati")
print(tagger.parse(text))
```

Note that you do not need to install MeCab using apt. That was the case previously, but has not been true for many years now. mecab-python3 includes MeCab.

The error you originally posted included `mydic` in the path, but that is not in the code you posted. I think that you were trying to use neologd but didn't have it installed. Unfortunately I cannot help you with neologd, but I strongly recommend against using it - it has not been updated in several years and is hard to use. Especially if you are just getting started, it is better to use `unidic-lite` or other prepackaged dictionaries.

Out of curiosity, what is the guide you are using?

**Comment by Yoshihiro-Gocho** [comment]
First of all, I am very sorry because I thought you were related to MeCab.
I am so grateful for volunteers like you.
And I am also very grateful for the many well-qualified advices. .
I'll try trial and error based on your advice.

Also, the introductory book I'm using now can be found at:
https://www.shoeisha.co.jp/book/detail/9784798142685

I'm really thankful to you.
