### ISSUE TITLE
DDL load failed

### ISSUE THREAD

**Issue by Cooperdevi** [SamuraiT/mecab-python3#96]
I am attempting to use mecab-python3 and I get an import error:

ImportError: DLL load failed while importing _MeCab: The specified module could not be found.

I am on Windows 10 and using Python3. I have ensured VS C++ RD is up to date and on path.

**Comment by polm** [comment]
Sorry you're having trouble with this. How did you install mecab-python3? On Windows, sometimes the required DLL is not installed. This generally happens in some kind of install outside of a virtualenv, though I have never been able to reproduce it. 

If you can check the directory where `mecab-python3` is installed, there should be a `libmecab.dll` file. If there isn't, that would be the cause of the problem.

Could you try installing `mecab-python3` in a virtualenv? That should work.
