### ISSUE TITLE
RuntimeError 

### ISSUE THREAD

**Issue by notduckiee** [SamuraiT/mecab-python3#97]
hey, i ran into runtimeerror and i did follow the guide and install vc redist. I have downloaded the x64 one (picture 2) and when i run the setup file, it showed up like the picture 3 and i clicked repair! I don't know if i did everything right but the error still occurs! 

I have no knowledge or expertise in programming or coding :/

![image](https://github.com/SamuraiT/mecab-python3/assets/143173021/47874cb1-566f-4984-abaa-060ea5291d8c)
![image](https://github.com/SamuraiT/mecab-python3/assets/143173021/ae608c7c-ac28-4d04-bc53-c0497cf3aa6f)
![image](https://github.com/SamuraiT/mecab-python3/assets/143173021/ed9352e1-4856-4aff-801b-faa8de531c4c)

**Comment by polm** [comment]
Please copy and paste terminal output as text. 

Did you install a dictionary, like this?

    pip install unidic-lite

**Comment by notduckiee** [comment]
I am really sorry that i don't know anything about these programming thing, so do you mind walking me through the process? 
I don't know what is terminal output and paste it into where? and what is a dictionary? ://

**Comment by polm** [comment]
I just realized you are using coqui TTS. I do not maintain that package, please ask them for help with it. 

Looking at their source, the latest version should no longer have this issue.
