### ISSUE TITLE
libmecab.dllのインストール場所について

### ISSUE THREAD

**Issue by tetlabo** [SamuraiT/mecab-python3#98]
Windowsでmecab-python3 1.0.7をインストールしました。importしようとすると、以下のエラーが出ました。VC++再頒布版はインストールしています。

```
>>> import MeCab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\MeCab\__init__.py", line 10, in <module>
    from . import _MeCab
ImportError: DLL load failed while importing _MeCab: 指定されたモジュールが見つかりません。
```
エラーメッセージで検索すると、以下の記事が見つかりました。

* [「ImportError: DLL load failed while importing \_MeCab: 指定されたモジュールが見つかりません。」の解決方法について](https://teratail.com/questions/4xsmllc4w388gv#reply-aszjisrmph8fzz)

記事の解答にあるように、`C:\Users\xxxxx\AppData\Roaming\Python\lib\site-packages\MeCab\libmecab.dll ` を `C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\MeCab` 下にコピーすると、正しくインポートができました。

**Comment by polm** [comment]
ご報告ありがとうございます。 https://github.com/polm/fugashi/issues/42 と同じ問題らしいですね。

virtualenvだと問題なく使えると思いますが、そうでない場合でも動かせるよう変更できるかどうか調べてみます。

**Comment by polm** [comment]
この問題について、未だにこちらで取れる対策が分からないので、一旦クローズします。

リンク先の情報によりますと、まずこの問題は公式Pythonでは起きず、Window StoreのPythonのみで起きるみたいなので、ユーザ側の対策の一つとしてはWindows StoreのPythonを使わないことです。

リンク先の情報だけでは明確ではありませんが、似たような問題でvirtualenvを使うと解決することもあったので、virtualenvの使用もおすすめします。
